### ISSUE TITLE
500 errors on submit reservation

### ISSUE THREAD

**Issue by vincentrgoossens** [Opifer/SmartEventManager#3]
Hi,

I am getting a 500 error on submitting a reservation,

do I miss something?

[reservationErrorXXX.pdf](https://github.com/Opifer/SmartEventManager/files/2778074/reservationErrorXXX.pdf)

Regards.Vincent

**Comment by rvanlaarhoven** [comment]
Hi @vincentrgoossens, this question should actually be asked to Voorraedt (the creator of SmartEventManager) itself. We just created a php wrapper to communicate with their API and cannot help you with api errors on their side.
