### ISSUE TITLE
Getting single standard reservation

### ISSUE THREAD

**Issue by atxvisions** [Opifer/SmartEventManager#5]
Hello,

I am trying to expand the client to be able to get single data based on their IDs but it seems like I am missing something.
When I use GET methods for this i get an error about setBody and when I change it to POST, the data returned is empty.

Is there a way to guide me into the right direction on how to get single reservations/standardreservations?
Thank you in advance

**Comment by rvanlaarhoven** [comment]
Hi @atxvisions ,
To be honest; we don't actually use this package anymore and I'm also not really up-to-date with the Smart Event Manager API specifications. So I'm afraid I can't help you with it.
It's probably a better idea to request any api documentation from Smart Event Manager itself and define your own api client.
